-- ============================================================
-- Fix error 42P17: "infinite recursion detected in policy for
-- relation \"usuarios\""
-- ============================================================
-- ** OBSOLETO / NO EJECUTAR. TODO el archivo esta neutralizado **
-- Este script DESHABILITABA RLS en 10 tablas, incluida `pedidos`. La base
-- actual tiene RLS habilitado en todas ellas; correr este archivo abriria
-- los pedidos de cualquier usuario a la clave anonima.
--
-- El plan final mantiene RLS habilitado y elimina SOLO las politicas
-- recursivas:
--    -> usar bloquear_anon_sensibles.sql
-- Para habilitar Realtime sobre `pedidos`:
--    -> usar habilitar_realtime.sql
-- ============================================================
-- Las políticas RLS actuales de este proyecto eran recursivas
-- (una política de la tabla `usuarios` vuelve a consultar `usuarios`),
-- lo que rompía TODAS las lecturas desde el cliente (app móvil, KDS, desktop)
-- con la clave anónima.
--
-- Para el flujo mínimo, el control de acceso se delegaba en los
-- microservicios (NestJS + service_role). Por eso se deshabilitaba RLS:
-- NO se crean columnas ni se cambian tipos de dato.
-- ============================================================
-- Los ALTER TABLE de abajo quedan comentados a propósito. Si alguien los
-- descomenta, cualquier cliente con la clave anon puede leer los pedidos,
-- las billeteras y los datos personales de todos los estudiantes.
--
-- ALTER TABLE public.usuarios           DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.roles              DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.cafeterias         DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.productos          DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.pedidos            DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.detalles_pedido    DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.pagos              DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.metodos_pago       DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.logs_validacion_qr DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.categorias         DISABLE ROW LEVEL SECURITY;

-- Para que Supabase Realtime emita cambios de la tabla PEDIDOS
-- (INSERT/UPDATE) hacia el KDS y la app móvil. Esto SÍ sigue siendo válido,
-- pero está también en database/fixes/habilitar_realtime.sql
-- (ALTER PUBLICATION supabase_realtime ADD TABLE public.pedidos;)
