apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: student-cdarwitg
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: gateway
