apiVersion: v1
kind: Service
metadata:
  name: inventario-service
  namespace: student-cdarwitg
  labels:
    app: inventario-service
    ms: inventario
spec:
  type: ClusterIP
  selector:
    app: inventario-service
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP